### ISSUE TITLE
CircleCI build fail

### ISSUE THREAD

**Issue by ericelliott** [ericelliott/react-pure-component-starter#15]
We're getting a failing build using Node 4.2.2 and npm v3.5.0 on CircleCI (works fine on my machine).

``` sh
TypeError: Cannot read property 'error' of undefined
    at OptionManager.mergeOptions (/home/ubuntu/react-pure-component-starter/node_modules/babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:28)
    at OptionManager.addConfig (/home/ubuntu/react-pure-component-starter/node_modules/babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
...
```

It appears to be that [an older version of Babel is trying to run the code](http://www.guyellisrocks.com/2015/11/babel-cannot-read-property-error-of.html). Which is odd, because we've got all the latest packages. Maybe some of the sub-dependencies need to be updated for Babel 6...

But it gets weirder.

When I log in with ssh and run:

``` sh
$ rm -rf node_modules && npm install && npm test 
```

The tests pass.

npm install generates a ton of warnings:

``` sh
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.5
npm WARN In dom-serializer@0.1.0 replacing bundled version of domelementtype with domelementtype@1.1.3
npm WARN In babel-plugin-syntax-object-rest-spread@6.1.18 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-plugin-syntax-jsx@6.1.18 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-plugin-syntax-function-bind@6.1.18 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-plugin-syntax-flow@6.1.18 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-plugin-syntax-do-expressions@6.1.18 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-plugin-syntax-class-properties@6.1.18 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-plugin-syntax-class-constructor-call@6.1.18 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-plugin-syntax-async-functions@6.1.18 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-plugin-syntax-export-extensions@6.1.18 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-plugin-transform-do-expressions@6.1.18 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-plugin-syntax-decorators@6.1.18 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-plugin-transform-react-display-name@6.1.18 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-plugin-transform-es2015-typeof-symbol@6.1.18 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-plugin-transform-es2015-spread@6.1.18 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-plugin-transform-es2015-literals@6.1.18 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-plugin-transform-es2015-destructuring@6.1.18 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-plugin-transform-function-bind@6.1.18 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-plugin-syntax-exponentiation-operator@6.1.18 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-plugin-transform-class-properties@6.2.2 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-messages@6.2.1 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-plugin-transform-es2015-for-of@6.1.18 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-plugin-transform-strict-mode@6.2.0 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-helper-regex@6.1.18 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-helper-optimise-call-expression@6.1.18 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-helper-replace-supers@6.2.0 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-helper-hoist-variables@6.1.18 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-helper-get-function-arity@6.2.0 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-helper-function-name@6.2.0 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-helper-remap-async-to-generator@6.1.18 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-helper-explode-assignable-expression@6.2.0 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-helper-define-map@6.2.0 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-helper-call-delegate@6.2.0 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-helper-builder-binary-assignment-operator-visitor@6.1.18 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-helper-bindify-decorators@6.1.18 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-helper-explode-class@6.1.18 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-plugin-transform-es2015-template-literals@6.1.18 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-plugin-transform-es2015-arrow-functions@6.1.18 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-plugin-transform-object-rest-spread@6.1.18 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-plugin-transform-export-extensions@6.1.18 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-plugin-transform-flow-strip-types@6.1.18 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-plugin-check-es2015-constants@6.2.0 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-plugin-transform-react-jsx-source@6.1.18 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In indent-string@2.1.0 replacing bundled version of repeating with repeating@2.0.0
npm WARN In is-number@2.1.0 replacing bundled version of kind-of with kind-of@3.0.2
npm WARN In semver-truncate@1.1.0 replacing bundled version of semver with semver@5.1.0
npm WARN In read-json-sync@1.1.0 replacing bundled version of graceful-fs with graceful-fs@3.0.8
npm WARN In babel-template@6.2.0 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-plugin-transform-class-constructor-call@6.1.18 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-plugin-transform-es2015-modules-commonjs@6.2.0 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-plugin-transform-es2015-unicode-regex@6.1.18 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-plugin-transform-es2015-object-super@6.1.18 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-plugin-transform-async-to-generator@6.1.18 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-helper-builder-react-jsx@6.2.0 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-plugin-transform-react-jsx@6.2.0 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-plugin-transform-decorators@6.1.18 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-plugin-transform-es2015-block-scoped-functions@6.1.18 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In esrecurse@3.1.1 replacing bundled version of estraverse with estraverse@3.1.0
npm WARN In find-up@1.1.0 replacing bundled version of path-exists with path-exists@2.1.0
npm WARN In randomatic@1.1.3 replacing bundled version of kind-of with kind-of@3.0.2
npm WARN In babel-plugin-transform-es2015-shorthand-properties@6.1.18 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-plugin-transform-es2015-sticky-regex@6.1.18 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-plugin-transform-es2015-function-name@6.1.18 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-plugin-transform-es2015-computed-properties@6.1.18 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-plugin-transform-exponentiation-operator@6.1.18 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In globby@3.0.1 replacing bundled version of pinkie-promise with pinkie-promise@1.0.0
npm WARN In globby@3.0.1 replacing bundled version of pinkie with pinkie@1.0.0
npm WARN In randomatic@1.1.3 replacing bundled version of is-number with is-number@2.1.0
npm WARN In babel-helpers@6.1.20 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-code-frame@6.1.18 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-plugin-transform-runtime@6.1.18 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-plugin-transform-es2015-block-scoping@6.1.18 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In stream-browserify@1.0.0 replacing bundled version of readable-stream with readable-stream@1.1.13
npm WARN In babel-plugin-transform-es2015-parameters@6.1.18 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-plugin-transform-es2015-classes@6.2.2 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In cliui@2.1.0 replacing bundled version of wordwrap with wordwrap@0.0.2
npm WARN In babel-register@6.2.0 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In doctrine@0.7.2 replacing bundled version of esutils with esutils@1.1.6
npm WARN In yargs@3.10.0 replacing bundled version of camelcase with camelcase@1.2.1
npm WARN In node-libs-browser@0.5.3 replacing bundled version of readable-stream with readable-stream@1.1.13
npm WARN In regexpu@1.3.0 replacing bundled version of esprima with esprima@2.7.0
npm WARN In babel-polyfill@6.2.0 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-plugin-syntax-trailing-function-commas@6.1.18 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In watchpack@0.2.9 replacing bundled version of async with async@0.9.2
npm WARN In express@4.13.3 replacing bundled version of qs with qs@4.0.0
npm WARN In babel-types@6.2.0 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In webpack-core@0.6.8 replacing bundled version of source-map with source-map@0.4.4
npm WARN In recast@0.10.39 replacing bundled version of source-map with source-map@0.5.3
npm WARN In recast@0.10.39 replacing bundled version of esprima-fb with esprima-fb@15001.1001.0-dev-harmony-fb
npm WARN In babel-generator@6.2.0 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-generator@6.2.0 replacing bundled version of source-map with source-map@0.5.3
npm WARN In enhanced-resolve@0.9.1 replacing bundled version of memory-fs with memory-fs@0.2.0
npm WARN In babel-plugin-transform-regenerator@6.2.0 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In mkdirp@0.5.1 replacing bundled version of minimist with minimist@0.0.8
npm WARN In webpack-hot-middleware@2.5.1 replacing bundled version of strip-ansi with strip-ansi@2.0.1
npm WARN In webpack-hot-middleware@2.5.1 replacing bundled version of ansi-regex with ansi-regex@1.1.1
npm WARN In source-map-support@0.2.10 replacing bundled version of source-map with source-map@0.1.32
npm WARN In sshpk@1.7.0 replacing bundled version of assert-plus with assert-plus@0.2.0
npm WARN In babel-core@6.2.1 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-core@6.2.1 replacing bundled version of source-map with source-map@0.5.3
npm WARN In uglify-js@2.6.1 replacing bundled version of source-map with source-map@0.5.3
npm WARN In uglify-js@2.6.1 replacing bundled version of async with async@0.2.10
npm WARN In babel-cli@6.2.0 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-cli@6.2.0 replacing bundled version of source-map with source-map@0.5.3
npm WARN In optimist@0.6.1 replacing bundled version of minimist with minimist@0.0.10
npm WARN In babylon@6.2.0 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In babel-traverse@6.2.0 replacing bundled version of babel-runtime with babel-runtime@5.8.34
npm WARN In js-yaml@3.4.5 replacing bundled version of esprima with esprima@2.7.0
npm WARN In htmlparser2@3.8.3 replacing bundled version of domutils with domutils@1.5.1
npm WARN In htmlparser2@3.8.3 replacing bundled version of entities with entities@1.0.0
npm WARN In htmlparser2@3.8.3 replacing bundled version of readable-stream with readable-stream@1.1.13
npm WARN In handlebars@4.0.5 replacing bundled version of source-map with source-map@0.4.4
npm WARN In webpack@1.12.9 replacing bundled version of esprima with esprima@2.7.0
npm WARN In webpack@1.12.9 replacing bundled version of supports-color with supports-color@3.1.2
npm WARN In eslint@1.10.2 replacing bundled version of user-home with user-home@2.0.0
npm WARN In eslint@1.10.2 replacing bundled version of minimatch with minimatch@3.0.0
npm WARN In eslint@1.10.2 replacing bundled version of espree with espree@2.2.5
```

But things seem to work anyway:

``` sh
> react-transform-boilerplate@2.1.1 pretest /home/ubuntu/react-pure-component-starter
> npm run lint


> react-transform-boilerplate@2.1.1 lint /home/ubuntu/react-pure-component-starter
> eslint source test


> react-transform-boilerplate@2.1.1 test /home/ubuntu/react-pure-component-starter
> babel-node ./test/index.js

TAP version 13
# Title
ok 1 should output the correct title text

1..1
# tests 1
# pass  1

# ok
```

**Comment by plum-dawg** [comment]
@ericelliott, did you resolve this?

**Comment by ericelliott** [comment]
Yes. CircleCI was caching some older modules.
